services:
  - parser: 
      pattern: /.*$
      methods: [POST,PUT,DELETE]
      content-type: application/json
      type: mock
      response:
        content-type: application/json
        status:
          POST: 201
          PUT: 200
          DELETE: 204
        body-type: request
  - parser: 
      pattern: /ping$
      methods: [GET]
      type: mock
      response:
        content-type: text/plain
        status:
          GET: 200
        body-type: fixed
        body: 'pong'
  - parser:
      pattern: /version$
      methods: [GET]
      type: mock
      response:
        status:
          GET: 200
        body-type: runnable
        response-lib: ../examples/plugins/runnable/runnable.so
        response-symbol: Version
  - parser:
      pattern: /test/pass$
      rewrite:
        - source: '/test(/.*)'
          target: '$1'
      methods: [GET]
      transform-lib: ../examples/plugins/transform/transform.so
      transform-symbol: AddHeader
      type: pass
      pass-base-uri: "http://localhost:55545"
